### ISSUE TITLE
'NoneType' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by billoty** [idlesign/django-yaturbo#2]
In the 'item_turbo' method i return the 'disambiguatingDescription' attribute that contains content with html.

    def item_turbo(self, item):
        return item.disambiguatingDescription

And i get error in feed.py

    AttributeError at /feeds/turbo
    'NoneType' object has no attribute 'startswith'

What should i actually return in this method to get sanitized content at the '/feeds/turbo' url. Rendered template?

**Comment by idlesign** [comment]
Thank you for the report.
String is expected, not ``None``.
Full stack trace would also be helpful.

**Comment by billoty** [comment]
Environment:
    
    
    Request Method: GET
    Request URL: https://example.org/feeds/turbo
    
    Django Version: 2.0
    Python Version: 3.6.5
    Installed Applications:
    ['example.apps.exampleConfig',
     'django.contrib.admin',
     'django.contrib.auth',
     'django.contrib.contenttypes',
     'django.contrib.sessions',
     'django.contrib.messages',
     'django.contrib.staticfiles',
     'django.contrib.sitemaps',
     'django.contrib.postgres',
     'django.contrib.sites',
     'import_export',
     'django_cleanup',
     'ckeditor',
     'django_filters',
     'sorl.thumbnail',
     'el_pagination']
    Installed Middleware:
    ['django.middleware.security.SecurityMiddleware',
     'django.contrib.sessions.middleware.SessionMiddleware',
     'django.middleware.locale.LocaleMiddleware',
     'django.middleware.common.CommonMiddleware',
     'django.middleware.csrf.CsrfViewMiddleware',
     'django.contrib.auth.middleware.AuthenticationMiddleware',
     'django.contrib.messages.middleware.MessageMiddleware',
     'django.middleware.clickjacking.XFrameOptionsMiddleware']
    
    
    
    Traceback:
    
    File "/home/admin/env/lib/python3.6/site-packages/django/core/handlers/exception.py" in inner
      35.             response = get_response(request)
    
    File "/home/admin/env/lib/python3.6/site-packages/django/core/handlers/base.py" in _get_response
      128.                 response = self.process_exception_by_middleware(e, request)
    
    File "/home/admin/env/lib/python3.6/site-packages/django/core/handlers/base.py" in _get_response
      126.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)
    
    File "/home/admin/env/lib/python3.6/site-packages/django/contrib/syndication/views.py" in __call__
      39.         feedgen = self.get_feed(obj, request)
    
    File "/home/admin/env/lib/python3.6/site-packages/django/contrib/syndication/views.py" in get_feed
      130.         link = add_domain(current_site.domain, link, request.is_secure())
    
    File "/home/admin/env/lib/python3.6/site-packages/django/contrib/syndication/views.py" in add_domain
      17.     if url.startswith('//'):
    
    Exception Type: AttributeError at /feeds/turbo
    Exception Value: 'NoneType' object has no attribute 'startswith'

**Comment by idlesign** [comment]
That one is related to Django syndication framework itself not to ``yaturbo``.
Documentation is here: https://docs.djangoproject.com/en/2.1/ref/contrib/syndication/#urls
You may want to enable Sites contrib.

**Comment by billoty** [comment]
The `sites` framework is enabled. The `get_absolute_url` method in the model is defined. Would you mind to provide the complete example of the `item_turbo` method? What should i actually return in this method?

**Comment by idlesign** [comment]
Sure. Example can be found in method _get_syndication_feed at https://github.com/idlesign/pythonz/blob/master/apps/generics/realms.py 
There's a dynamic class creation, but it won't make a big difference.
Actual content is in item's turbo_content.

**Comment by civilianmanyu** [comment]
While using RiverGIS on QGIS, I am getting the following error, please help

Creating RAS GIS Import file from HEC-RAS model geometry...
An error has occurred while executing Python code: 

AttributeError: 'NoneType' object has no attribute 'startswith' 
Traceback (most recent call last):
  File "C:/Users/abhib/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\rivergis\rivergis.py", line 112, in 
    self.ui.actionRASCreateRASGISImport.triggered.connect(lambda: r1d.ras1dCreateRasGisImportFile(self))
  File "C:/Users/abhib/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\rivergis\ras1dFunctions.py", line 476, in ras1dCreateRasGisImportFile
    sdf = rgi.gis_import_file()
  File "C:/Users/abhib/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\rivergis\ras_gis_import.py", line 102, in gis_import_file
    imp += self.storage_areas.build_storage_areas()
  File "C:/Users/abhib/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\rivergis\ras_gis_import.py", line 754, in build_storage_areas
    pnts = RasGisImport.unpack_wkt(s['wkt'])
  File "C:/Users/abhib/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\rivergis\ras_gis_import.py", line 78, in unpack_wkt
    if wkt.startswith('POINT'):
AttributeError: 'NoneType' object has no attribute 'startswith'


Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.12.1-București București, 121cc00ff0 

Python Path:
C:/Users/abhib/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\wnt
C:/Users/abhib/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\WaterNetAnalyzer-master
C:/Users/abhib/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\networks
C:/Users/abhib/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\contour
C:/PROGRA~1/QGIS3~1.12/apps/qgis/./python
C:/Users/abhib/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/abhib/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS3~1.12/apps/qgis/./python/plugins
C:\PROGRA~1\QGIS3~1.12\apps\Python37
C:\PROGRA~1\QGIS3~1.12\apps\Python37\Scripts
C:\Program Files\QGIS 3.12\bin\python37.zip
C:\PROGRA~1\QGIS3~1.12\apps\Python37\DLLs
C:\PROGRA~1\QGIS3~1.12\apps\Python37\lib
C:\Program Files\QGIS 3.12\bin
C:\Users\abhib\AppData\Roaming\Python\Python37\site-packages
C:\PROGRA~1\QGIS3~1.12\apps\Python37\lib\site-packages
C:\PROGRA~1\QGIS3~1.12\apps\Python37\lib\site-packages\win32
C:\PROGRA~1\QGIS3~1.12\apps\Python37\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS3~1.12\apps\Python37\lib\site-packages\Pythonwin
C:/Users/abhib/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\abhib\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\GeoTrace\tools
C:/Users/abhib/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\go2streetview
C:\Users\abhib\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\go2streetview\res
C:\Users\abhib\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\midvatten
C:\Users\abhib\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\midvatten\tools
.

**Comment by idlesign** [comment]
@civilianmanyu I'm afraid it doesn't relate to `django-yaturbo`.
Maybe https://github.com/erpas/rgis may help.

**Comment by idlesign** [comment]
Considered closed. 
Feel free to reopen if required.
